name: ci

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Should Publish
        if: github.event_name == 'push'
        shell: bash
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "UPT_PUBLISH=true" >> "$GITHUB_ENV"
          else
            echo "publish is only enabled by tagging with a release tag"
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build UnityPackageTool
        if: ${{ !env.UPT_PUBLISH }}
        run: dotnet build src/upt -c Release

      - name: Build Packages and Publish
        if: ${{ env.UPT_PUBLISH }}
        shell: bash
        run: |
          dotnet tool install -g dotnet-releaser
          dotnet-releaser run --github-token ${{secrets.GITHUB_TOKEN}} src/dotnet-releaser.toml
